### ISSUE TITLE
Setup-Azure (Module 6)

### ISSUE THREAD

**Issue by marciogmorales** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#152]
We´re facing problems running Setup-Azure for Module 6.

Log Attached.

[Setup-Azure-6.zip](https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/files/953197/Setup-Azure-6.zip)

**Comment by polichtm** [comment]
When you run Setup-Azure and select lab 6, the script will prompt you to provide credentials of the Service Admin account of your Azure subscription in order to authenticate. The errors in the log file you provided seem to indicate that you have not successfully authenticated. Can you verify whether this is actually the case?

**Comment by bwer432** [comment]
Hello! You likely need to update your PowerShell modules in your MIA-CL1 machines. That resolved this issue in my systems. The Get-AzureRmLocation cmdlet does not exist in some versions of the AzureRM.Resources module. Do a: `Get-Module AzureRM.Resources -ListAvailable` to see what version you have. Version 3.6.0 works with this Setup-Azure for module 6. I hope this helps. Good luck!

**Comment by marciogmorales** [comment]
Yeah. the  Get-AzureRmLocation was resolved by the upgraded that you told above. Thanks.
