### ISSUE TITLE
Lab of module 8, Ex 2, Task 2. Configure RDP Access

### ISSUE THREAD

**Issue by HollyDickson** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#157]
The following commands give this error:
$cloudservice = '20533clab08'
$username = 'student'
$securepassword = 'Pa55w.rd1234' | convertto-securestring -asplaintext -force
$expirationdate = $(get-date).adddays(31)
$credential = new-object System.Management.Automation.PSCredential username,securepassword
new-object : Cannot find an overload for "PSCredential" and the argument count: "2".
At line:1 char:15
+ ... redential = new-object System.Management.Automation.PSCredential user ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

Running $securepassword gives this output:
System.Security.SecureString

This lab worked last time I gave the class. Has the lab changed?

Thanking you in advance

**Comment by renaudwangler** [comment]
Hello !
 
Why does your line $credential=New-Object[..] contain "username,securepassword" instead of "$username,$securepassword" ?
I'm not sure the command would recognize the variables without the $ sign
 
 
greetings from France
 
Renaud WANGLER
Formateur
Ib - groupe CEGOS
Tél. : +33 6 83 00 77 14

-------------------Informations légales------------------- 
Ce message et toutes les pièces jointes sont confidentiels et établis à l'attention exclusive de ses destinataires. 
Le présent mail ainsi que toutes les informations qu'il contient ne peuvent être considérés comme un engagement de quelque nature que ce soit de la part d'ib - groupe Cegos, tout accord devant être formulé par écrit. 
Le message reste la propriété exclusive d' ib - groupe Cegos. 
Toute utilisation ou diffusion non autorisée est interdite. 
ib - groupe Cegos décline toute responsabilité au titre de ce message s'il a été altéré, déformé ou falsifié.

________________________________

**Comment by HollyDickson** [comment]
Hello Renaud,
You're right of course! But here's why:
5. Next, execute the following script by typing each of the following commands at the Windows PowerShell prompt and pressing Enter: ``` $serviceName = 'Your-cloud-service'
$userName = 'Student'
$securePassword = 'Pa55w.rd1234' | ConvertTo-SecureString -AsPlainText -Force
$expirationDate = $(Get-Date).AddDays(31)
$credential = New-Object System.Management.Automation.PSCredential userName,securePassword
Set-AzureServiceRemoteDesktopExtension -ServiceName $serviceName -Credential $credential -
Expiration $expirationDate -Slot Production
Set-AzureServiceRemoteDesktopExtension -ServiceName $serviceName -Credential $credential -
Expiration $expirationDate -Slot Staging ```
where Your-cloud-service designates the name of the cloud service you deployed earlier in this lab

It still works from the Classic portal to activate RDP (I'm sure the lab was that way before and it's easier for the students to follow what they are doing)

The labs and answer key need correcting. 

Greeting from the UK.

**Comment by renaudwangler** [comment]
From my point of view, everytime we can avoid students using the (old) classic portal is a nice improvement ;)
I don't see any problem with the poweshell in the current version of the Labs and answer key : perhaps a format problem during the export ?

**Comment by polichtm** [comment]
That's correct - pls refer to https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/blob/master/Instructions/20533C_LAB_AK_08.md for the script
thnx
Marcin

**Comment by HollyDickson** [comment]
Yes the on file is OK. So following the procedure to convert to Word is completely pointless.

**Comment by polichtm** [comment]
Which procedure are you referring to?
thnx
Marcin

**Comment by HollyDickson** [comment]
Converting the labs to Word documents

**Comment by polichtm** [comment]
GitHub is intended to serve as the point of reference in case of in case of issues like this one.  We'll look into addressing the discrepancies in the Word conversion
thnx
Marcin
