### ISSUE TITLE
Lab Steps (Scripts) Module 10

### ISSUE THREAD

**Issue by Michtian** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#179]
There are two files that need to be edited for the lab to work in Module 10. This is what I have found to work thus far.

In Module 10 you will need to replace 2 files.
Show-SubscriptionARM replaces the version of itself in D:/Modules/Show-SubscriptionARM/

The second file will replace the file with the same name:
Setup-20533C10Lab.ps1 will repalce the version of itself in D:/LabFiles/Lab10/Starter

[Scripts.zip](https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/files/1149459/Scripts.zip)

**Comment by Michtian** [comment]
References to Subscription based commands with property "SubscriptionID" seem to only accept "ID", however AzureRMContext based commands still use SubscriptionID.

**Comment by Michtian** [comment]
![fixed](https://user-images.githubusercontent.com/24464234/28227888-0652abc8-68aa-11e7-828a-beca5f62f22c.JPG)

Those changes do seem to fix the issue.

**Comment by polichtm** [comment]
Are you using the lab VM with the version of Azure PowerShell that is included in the image?
thnx
Marcin

**Comment by erohner** [comment]
Lab 10: On line 51of file Setup-20533C10Lab.ps1 .SubscriptionId needs to be .id

Very irritating as if the person who wrote the code actually tested it, they would have found out they ISSUE.

I teach Azure all the time, and these rookies who are writing the courses need a little more training on course ware creation.

**Comment by polichtm** [comment]
Are you using the lab VM with the version of Azure PowerShell that is included in the image?
thnx
Marcin

**Comment by erohner** [comment]
We are using Learn on Demand, which has nothing to do with the issue.

The file on LOD and GitHub both have the same issue. SubscriptionID is not
a valid property, ID is the valid property.

This error on line 51 fails the entire script.

It is obvious to me that who ever wrote that line of code did not test it.

As an instructor on the front line with students, it is a disgusting thing
to happen.

My question would be why was the code not tested, or even run one time,
before deployment.

That is very careless and unprofessional. That person should have a job
writing code, that makes others look bad because they are on the front
lines not the code writer.

Send the code writer to my class and have him/her explain to the students,
that pay a lot of money to attend a training, why he/her did not test the
code.

I wish I could Microsoft a bill for all the labs with Azure I have to fix.

It also makes Microsoft look bad and makes students wonder, why should we
even use Azure!

**Comment by polichtm** [comment]
So you are stating that the following does not work for you - correct?
PS C:\> (Get-AzureRmContext).Subscription.SubscriptionId
7a3b1f8a-90bd-4524-bbd8-8704d5c4987c
If so, pls post the output of 
(Get-Module -Name Azure).Version

**Comment by erohner** [comment]
Nope that is not a valid command, there is no property for subscriptionID,
it is ID.


The Get-Module command produced no output.

**Comment by erohner** [comment]
This is very strange, when I run the cmdlet get-azurermcontext is does
produce an output of subscriptionId.

I have 12 students, the lab setup failed for all of them. The only way it
worked without errors was to change subscriptionid to id on line 51.

**Comment by erohner** [comment]
[image: Inline image 1]

**Comment by erohner** [comment]
[image: Inline image 1]

**Comment by erohner** [comment]
And this is my final proof that I am right and you are wrong.

[image: Inline image 1]

**Comment by erohner** [comment]
And here is more proof that who ever wrote the code did test it. I would
like to tell them their face how hard it is in class when the writer does
not do their job.

Now stop blaming it on the version or me or my students, it is clearly the
problem of a course writer who does not pay attention to detail.

[image: Inline image 1]

**Comment by erohner** [comment]
That command is not valid. this will fail in the labs: (Get-AzureRmContext).Subscription.SubscriptionId
This will succeed: (Get-AzureRmContext).Subscription.Id
this (Get-AzureRmContext).Subscription.SubscriptionId will get you the output of nothing
this (Get-AzureRmContext).Subscription.ID will get you the output of subscription id
this (Get-AzureRmContext).Subscription will get you the output of 
Name:
Id:
TenantId:
State:

this (Get-AzureRmContext) will get you the output of 
Environment:
Account:
TenantId:
SubscriptionId:
SubscitptionName:
CurrentStorageAccount

Therefore Microsoft stop blaming it on the version, it is clearly your code that does not work.
I have been teaching Microsoft courses for two decades, never have I seen such poor effort put into making the course work.

This is another good reason many MCTs do not want to teach an Azure class, as they never work correctly.

**Comment by bwer432** [comment]
Hello! I will research this in the LOD setup and adjust the versions. I was already looking into this earlier today, but haven't finished yet.

Thanks,
++brad;

----------------------------
Bradford Werner
Technical Evangelist
Werner Training and Consulting, Inc.

**Comment by erohner** [comment]
While that is being researched may I offer a suggestion or two.

The early labs focus too much on Powershell and not enough on the concepts.
Too much time is spent fixing errors that the students make or even worse
the errors that are baked into the labs.

If the student was shown more of the Portal in the labs, and then maybe an
exercise on how a previous action was performed in the portal is performed
in Powershell.

The labs are more of a debug session, which confuses the students, and
takes away from the class. The person(s) who is responsible for this course
has taken on a huge task. The task is keeping up with the Portal changes in
relation to the labs. It is great we have those cmdlets but let's train the
student first on how to use Azure and it's Portal, then move them on to
Powershell.

**Comment by vkarlis** [comment]
Thanks erohner for pointing this out. I've spent way too much time in classes where we are debugging the course examples then necessary. 

Regards,
Bill Karlis

**Comment by grantcarthew** [comment]
Hi @erohner and @vkarlis 
This issue is titled "Lab Steps (Scripts) Module 10". Please open a new issue if you with to take the conversation off topic.

**Comment by erohner** [comment]
The topic of the conversation is the poorly written labs, it includes and
is not limited to lab10.

If you wish to direct people to do as you wish you might want to use proper
grammar, as I can only assume what your statement is saying.

It appears you had nothing to contribute to the huge problems in course
20533, have you ever taught it?

**Comment by polichtm** [comment]
erohner,
this is NOT a place for insults. Attempts to point out how inferior other people are while extolling one's own superiority do not belong on this forum. 
Any constructive feedback is welcome. If you have something to share, then provide specifics and state them in a civil manner. 
The issue you raised regarding one of the scripts in module 10 is being looked into
rgds
Marcin

**Comment by erohner** [comment]
Pointing out facts is not an insult.

**Comment by bwer432** [comment]
Hello @erohner et al,

This lab 10 issue should be fixed for system using LOD.

I have updated the LOD setup so that the Setup-20533C10Lab.ps1 script runs successfully. Also changed was the Show-AzureSubscriptionARM.psm1. Those changes are localized to the LODS are which is using version 3.1.0 (not the latest 3.2.1) of the AzureRM.Profile module. For systems using version 2.8.0 and earlier of that module, Get-AzureRmSubscription returns objects with SubscriptionId and SubscriptionName properties, while versions 3.0.0 of AzureRM.Profile and newer return objects with Id and Name properties. 

Planning ahead for when other environments are updated with current or near-current versions of the AzureRM.* modules, I will (but have not yet) create a branch in the main repo with these changes.

Please let me know of any questions or suggestions.

Thank you,
++brad; (@bwer432)

----------------------------
Bradford Werner
Technical Evangelist
Werner Training and Consulting, Inc.

**Comment by polichtm** [comment]
Brad, 
would you mind clarifying why PowerShell modules are updated in the first place? The VM image is thoroughly rested prior to the release of the course - updating modules independently in LOD is bound to continue to result in issues like this one.
rgds
Marcin

**Comment by erohner** [comment]
Awesome, now if we can get Microsoft to clean up their test and match up to
their changes and deprecations.
This does show Microsoft has not solidified their PowerShell Azure
Environment, and we know they are changing the Portal, and field labels
within the Portal frequently.
There is nothing stable about the Azure environment either declarable  or
programmable.

**Comment by polichtm** [comment]
The scripts have been updated to account for changes introduced in AzureRM.Profile, as described by Brad. 
This issue underscores the importance of using the version of Azure PowerShell version (and the corresponding modules) referenced in the lab guide. Pls make sure to take into account going forward.
