### ISSUE TITLE
Module 2 add-20533denvironement problem

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#307]
Running script asks for VirtualMachineSize. This didn't used to happen. 
Should this not be built into the script?
What is the size to give?

**Comment by itbland** [comment]
Not all sizes are available in all datacenters, particularly if you are using AzurePass. They changed the scripts so you can have the students specify a datacenter and size that you know will work in that datacenter (AzurePass students were having a terrible time with scripts failing.) So, after you determine the best datacenter and then find a size VM (Close to the size that had been specified in the past) that can be used by the AzurePass.

-ItBland

________________________________

**Comment by polichtm** [comment]
Karine - that precisely the reason. 
The prompt for the VM size is intentional. The reason for it is lack of consistency in regard to availability of VM sizes across Azure regions – in particular, when using an Azure Pass subscription. In such cases, hardcoding the VM size into a template would cause the deployment to fail.
At this point, it is the responsibility of the instructor to determine which sizes are available and advise students when they run the provisioning scripts
rgds
Marcin
