### ISSUE TITLE
Lab 6: Ex 3: Task 6: Un-register of Backup Server does not complete, prevents Recovery Services Vault deletion.

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#335]
Replace Lab 6: Ex 3: Task 6 steps with the following:

Task 6: Delete the Recovery Services Vault:
1.	Switch to the Azure portal, navigate back left to the Recovery Services vault blade, scroll down to the MANAGE section and click Backup Infrastructure. Then click Protected Servers.
2.	On the PROTECTED SERVERS blade, click Azure Backup Agent.
3.	On the Protected Servers (Azure Backup Agent) blade, verify that there is an entry referencing MIA-CL1. Click the MIA-CL1. link.
4.	On the MIA-CL1. blade, click Delete.
5.	On the Delete blade, in the TYPE THE SERVER NAME text box, type: MIA-CL1. and click Delete. This should de-register the server. Note: MIA-CL1. is case-sensitive and includes the period. If the Delete (de-register) does not complete, the Recovery Services Vault cannot be deleted later. If this happens just continue.
6.	Scroll back left to the recovery services vault blade and click Overview. You may have to scroll up also.
7.	Click Delete. When prompted to confirm, click Yes. Wait for the vault to be deleted. If the Delete (de-register) did not complete earlier, the Recovery Services Vault cannot be deleted. If this happens just continue.

**Comment by polichtm** [comment]
updated

**Comment by begler1** [comment]
Thanks for the speedy update. However, I checked the update and it was not applied correctly. Task 6 should be completely replaced with the accurate steps above. Thanks. The previous steps encounter a bug in the Azure Portal and does not work.

**Comment by polichtm** [comment]
Would you mind clarifying what specifically is inaccurate in the current content of task 6?
For example, note that step 1 you provided starts with “Switch to the Azure portal”. This is not accurate, since the last step of task 5 involves the use of Azure portal (and you are already on the Recovery Services vault blade).
In addition, isn’t the link to MIA-CL1. In lower case?
Rgds
Marcin

**Comment by polichtm** [comment]
Really appreciate helping out – and my intention is to certainly address the current bug in the portal.
Would you mind clarifying though which specific step should be modified in the current procedure in order to bypass the bug you are referring to?

Would the following work?


  1.  In the Azure portal, on the Recovery Services vault blade, scroll down to the MANAGE section and click Backup Infrastructure. Then click Protected Servers.
  2.  On the PROTECTED SERVERS blade, click Azure Backup Agent.
  3.  On the Protected Servers (Azure Backup Agent) blade, verify that there is an entry referencing MIA-CL1. Click the mia-cli1. link.
  4.  On the mia-cl1. blade, click Delete.
  5.  On the Delete blade, in the TYPE THE SERVER NAME text box, type mia-cl1. and click Delete. This should de-register the server. Note: the server name is case-sensitive and includes the period. If the Delete (de-register) does not complete, the Recovery Services Vault cannot be deleted later. If this happens just continue.
  6.  Scroll back left to the recovery services vault blade and click Overview. You may have to scroll up also.
  7.  Click Delete. When prompted to confirm, click Yes. Wait for the vault to be deleted. If the Delete (de-register) did not complete earlier, the Recovery Services Vault cannot be deleted. If this happens just continue.
Rgds
Marcin

**Comment by polichtm** [comment]
You are correct. I updated the content to match the sequence of steps you provided
Rgds
Marcin
