### ISSUE TITLE
Error in New-20533D03LabVM2.ps1 in E:\Labfiles\Lab03\Starter

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#336]
Line 21
"$osDiskType = 'StandardLRS'" should be "$osDiskType = 'Standard_LRS'"

**Comment by SignFinder** [comment]
Confirmed

**Comment by polichtm** [comment]
updated

**Comment by renaudwangler** [comment]
In addition all my students needed to use "StandardLRS". The new value of "Standard_LRS" gave an error on every try...
FYI : all student used the "West Europe" datacenter.

**Comment by polichtm** [comment]
Agreed - I'm seeing the same behavior. Updated
tbkobberoe and SignFinder  - pls post the error message you're getting
rgds
Marcin

**Comment by tbkobberoe** [comment]
When running last line (59) this error is thrown. It doesn't show when using Standard_LRS. Location West Europe
![standardlrs](https://user-images.githubusercontent.com/29890863/41348059-d40f2768-6f0b-11e8-8f49-0f9d44573035.jpg)

**Comment by polichtm** [comment]
This has been resolved by changing line 21 to:
$osDiskType = (Get-AzureRmResource -ResourceGroupName $rgName -ResourceType Microsoft.Compute/disks)[0].Sku.name
Pls let me know if you are still seeing any issues
rgds
Marcin

**Comment by haskoe** [comment]
Get this with region westeurope

New-AzureRmVM : Requested operation cannot be performed because storage account type 'Premium_LRS' is not supported for VM size 'Standard_D1_v2'.
ErrorCode: InvalidParameter
ErrorMessage: Requested operation cannot be performed because storage account type 'Premium_LRS' is not supported for VM size 'Standard_D1_v2'.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : f99cfef5-db72-40b0-8657-ac2bec93fce9
At line:60 char:1
+ New-AzureRmVM -ResourceGroupName $rgName -Location $location -VM $vmC ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

**Comment by Nailzy** [comment]
Line 57 fails because the input is expecting StandardLRS or PremiumLRS, but the variable being created in Line 21 is putting it as Standard_LRS or Premium_LRS.

PS C:\Users\Student> $osDiskType
Standard_LRS

Set-AzureRmVMOSDisk : Cannot bind parameter 'StorageAccountType'. Cannot convert value 
"Standard_LRS" to type "Microsoft.Azure.Management.Compute.Models.StorageAccountTypes". Error:
"Unable to match the identifier name Standard_LRS to a valid enumerator name. Specify one of the
following enumerator names and try again:
StandardLRS, PremiumLRS"
At E:\Labfiles\Lab03\Starter\New-20533E03labVM2.ps1:57 char:99
+ ... ame -DiskSizeInGB $osDiskSize -StorageAccountType $osDiskType -Create ...
+ ~~~~~~~~~~~
+ CategoryInfo : InvalidArgument: (:) [Set-AzureRmVMOSDisk], ParameterBindingExcepti
on
+ FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Compute.Set
AzureVMOSDiskCommand
