### ISSUE TITLE
"Error" in Module 4 Lab A Exercise 1 LAK description

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#337]
In 20533D_LAB_03.md it says
Size: any available size with one or two vCPUs
In 20533D_LAB_AK_03.md
In Task 1 it says "On the Choose a size blade, select any of available sizes with one or two vCPUs, and then click Select"

If you choose 2 vCPUs you won't have enough as the Azure pass is limited to 10

**Comment by edbakermct** [comment]
A god teaching point is to show students on day 1 how to raise available cores in a region using a support request . Then all works fine only an issue since subs now split the 20 core limit between regions

Sent from iOS Outlook<https://aka.ms/qtex0l> protected by Microsoft Enterprise Mobility and Security
________________________________

**Comment by tbkobberoe** [comment]
Thx Ed, I've tried earlier to ask for a raise, and that didn't go as fast as you describe. I may try it again though

**Comment by edbakermct** [comment]
Each time I do it I ask for 20 of a specific type in a region and it approves on 3 minutes , automated only had none query for a student requesting 100 ,

Sent from iOS Outlook<https://aka.ms/qtex0l> protected by Microsoft Enterprise Mobility and Security
________________________________

**Comment by polichtm** [comment]
updated instructions (#338)
