### ISSUE TITLE
Lab 8 subscription restrction

### ISSUE THREAD

**Issue by Berrichon** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#340]
within the lab 8B the student trial subscription do no permit the  recovery vault creation on another site.

I've not found yet any solution to this issue.

**Comment by polichtm** [comment]
Closing due to lack of response and inability to reproduce the issue

**Comment by alihk79** [comment]
hello,
\
While I am using the Azure Pass, it didn't work, My main VM was created in westeurope, when you go to replicate then you need to choose target location, it just shows you 4 target locations an your location doesn't exist into them (the four locations are UK west- UK SOuth- France Central- North Europe) Note that my vault was created in west US 2, it gave me error " Your subscription doesn't support createion of virtual machine in …. " this what is happening with me and my trainees, really I am embarrassing from such issues

**Comment by alihk79** [comment]
The problem is at the beginning of any lab implementation my azure subscription gave me just 6 Azure Region to select one of them East US - South Central US - West Central US - West US 2 - West Europe - Southest Asia ) and after creating the vault and click on replicate the target location exists, are UK west - UK South - France central - North Europe and these four locations don't exist in my subscription. so what should I do  ?? it happened with my students, and we are wasting our time by testing the lab, your fast response is highly appreciated
Regards
