### ISSUE TITLE
Co-administrator must be nonexisting

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#55]
Is it possible to add a note or warning to the lab of module 1, NOT to use the account of a classmate (with an Azure subscription) nor an email address with a paid subscription? 
It give strange behaviour in power shell when students are working in the same subscription (and not knowing that they do...). More dangerous if you suddenly work on a paid subscription without knowing.

Or otherwise emphasise 'random' and ensure that no subscription exists for the co-admin.

I know and always warn my students, however some don't...

**Comment by polichtm** [comment]
Using the same subscription by multiple students is bound to cause issues due to the naming conflicts - that should be rather clear but we can consider adding a note that would make it clear. 
Can you clarify what specifically is the issue with using a paid subscription that you are referring to? The provisioning scripts clearly identify the subscription in which the resources will be provisioned - in addition there are notes within the content at the beginning and the end of each module that point out the "destructive" nature of "Reset-Azure".

**Comment by molenaar** [comment]
Students think they use their azure pass and are probably not aware they add their paid subscription using the co-admin exercise. 

It must be clear to students what the consequences are by adding co-admin.

Just add a double warning because reset-azure is dangerous for people not knowing what they are doing.

**Comment by polichtm** [comment]
Reset-Azure does prompt you to choose the subscription that you want to run it against. Students would have to explicitly select the paid subscription rather than Azure Pass. 
As I mentioned, there are already multiple notes throughout the entire content (at least two in each module) which point out that running Reset-Azure would delete content of the subscription that students selects. If, in your opinion, this does not suffice, what else would you want to see?

**Comment by molenaar** [comment]
It's more about the impact of adding a co admin.

**Comment by polichtm** [comment]
Marcel - I'm still not sure what specifically you would want to include. I don't recall anything in the course that would imply that students should add a co-admin. Could you clarify?
