### ISSUE TITLE
Multiple storage accounts cause script to fail

### ISSUE THREAD

**Issue by SiloReed** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#63]
In Lab 3 I created a VM and left the Monitoring option on (that's the default). This caused two storage accounts to be created:
StorageAccountName    Kind ResourceGroupName Location
------------------    ---- ----------------- --------
resdevrgdiag762    Storage resdevrg          eastus  
resdevrgdisks641   Storage resdevrg          eastus  

The PowerShell script "D:\Labfiles\Lab03\Starter\CreateRmVM.ps1" has a bug in line 43. The line looks like this:
$storageAccount   = Get-AzureRmStorageAccount | Where-Object {($_.Location -eq $location) -and ($_.ResourceGroupName -eq $rgName)} 

Line 43 assumes that a singleton is returned when in fact an array is returned (at least in my case). The fix is to comment out line 43 and add these 2 lines after line 43:
# Fixes bug if there is more than one storage account in the resource group
$storageAccount   = (Get-AzureRmStorageAccount | Where-Object {($_.Location -eq $location) -and ($_.ResourceGroupName -eq $rgName) -and ($_.StorageAccountName -like $("*" + $rgName.ToLower() + "disks*"))})[0] 

Essentially, this will make sure that the storage account used is a singleton that contains "resdevrgdisks" in the StorageAccountName. 

A similar problem exists in "D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1", if more than one Storage Account exists (because VM monitoring was enabled) then the script fails. The bug is in line 7. Comment it out and insert this one in its place:
$storageAccount   = (Get-AzureRmStorageAccount | Where-Object {($_.ResourceGroupName -eq $resourceGroupName) -and ($_.StorageAccountName -like $("*" + $resourceGroupName.ToLower() + "disks*"))})[0]

**Comment by polichtm** [comment]
SiloReed
I assume you meant
$storageAccount = (Get-AzureRmStorageAccount | Where-Object {($_.Location -eq $location) -and ($_.ResourceGroupName -eq $rgName) -and `
                    ($_.StorageAccountName -like $($rgName.ToLower() + "disks*"))})[0] 
I'll update the scripts accordingly

**Comment by SiloReed** [comment]
I actually had an asterisk enclosed in the first set of double quotes. Not sure how I pasted it without the asterisk. I don't think it's required, so your solution probably works. I don't think ".ToLower()" is required with -like because I think -like is case insensitive, but you can never be too careful, right? ;)

**Comment by polichtm** [comment]
certainly won't hurt... ;)
appreciated....

**Comment by KoprowskiT** [comment]
I had same problem on my course this week.
We made small change on lfy in the labs:

AT THE END OF LINE 43 WE ADDED:  -and ($_.storageaccountname -match "disks")}

But of course changing scipt in total (for lab3 and lab4) will be much better option.



Best Regards

Tobiasz

De: Jeff Reed [mailto:notifications@github.com]
Enviado el: fimmtudagur, 20. október 2016 22:09
Para: MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions <20533-ImplementingMicrosoftAzureInfrastructureSolutions@noreply.github.com>
Asunto: [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions] Multiple storage accounts cause script to fail (#63)


In Lab 3 I created a VM and left the Monitoring option on (that's the default). This caused two storage accounts to be created:
StorageAccountName Kind ResourceGroupName Location

________________________________

resdevrgdiag762 Storage resdevrg eastus

resdevrgdisks641 Storage resdevrg eastus

The PowerShell script "D:\Labfiles\Lab03\Starter\CreateRmVM.ps1" has a bug in line 43. The line looks like this:
$storageAccount = Get-AzureRmStorageAccount | Where-Object {($.Location -eq $location) -and ($.ResourceGroupName -eq $rgName)}

Line 43 assumes that a singleton is returned when in fact an array is returned (at least in my case). The fix is to comment out line 43 and add these 2 lines after line 43:

Fixes bug if there is more than one storage account in the resource group

$storageAccount = (Get-AzureRmStorageAccount | Where-Object {($.Location -eq $location) -and ($.ResourceGroupName -eq $rgName) -and ($_.StorageAccountName -like $("" + $rgName.ToLower() + "disks"))})[0]

Essentially, this will make sure that the storage account used is a singleton that contains "resdevrgdisks" in the StorageAccountName.

A similar problem exists in "D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1", if more than one Storage Account exists (because VM monitoring was enabled) then the script fails. The bug is in line 7. Comment it out and insert this one in its place:
$storageAccount = (Get-AzureRmStorageAccount | Where-Object {($.ResourceGroupName -eq $resourceGroupName) -and ($.StorageAccountName -like $("" + $resourceGroupName.ToLower() + "disks"))})[0]

**Comment by polichtm** [comment]
Tobiasz,
this has already been implemented
rgds
Marcin
