### ISSUE TITLE
Lab 3 Task 2: Use Azure PowerShell to create a virtual machine, it gives error when running script

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#78]
Lab 3 Task 2: Use Azure PowerShell to create a virtual machine, it gives error when running script CreateRmVM.PS1

The error is "New-AzureRMVM – This operation is nor supported for a relative URI"

![image](https://cloud.githubusercontent.com/assets/24426530/20957079/a108911a-bc88-11e6-8727-aa6a143219ba.png)

**Comment by polichtm** [comment]
I cannot reproduce this error. Pls rerun the script, but this time, capture the output by running first the following: 
Start-Transcript -Path "D:\Logs\CreateRmVM.log" -IncludeInvocationHeader -Append -Force
and post the resulting log file.

**Comment by stuggie1** [comment]
In my experience, the "relative URI" error arises when Reset-Azure wasn't run and there's a previous storage account in the subscription.  I think an earlier commit updated the CreateRmVM.ps1 script to account for multiple storage accounts, so it's possible an older version of the script is being run here.

**Comment by polichtm** [comment]
The error message seems to indicate that the storage account does not exist - which would imply that the first part of the exercise 1 (which involves creating an Azure VM by using the Azure portal) was not completed correctly - e.g. the VM was deployed to another region or to another resource group. Assuming that was the case, the following line of the script
$storageAccount	= Get-AzureRmStorageAccount | Where-Object {($_.Location -eq $location) -and ($_.ResourceGroupName -eq $rgName)}
would not return a valid reference to the storage account. 
In any case, considering that this error seems to be isolated to this particular case, I'd need more information to effectively troubleshoot it.
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response from dpapkin

**Comment by molenaar** [comment]
Its better to create an new storage account instead of assuming a storage account exists from a previous exercise. Microsoft changes the user interface of the portal all the time by enabling settings for default, like a the naming of storage accounts and enabling a storage account for logging.

So getting an excisting storage account is not a good idea. Remove the get-azurermstorageaccount function and replace it by new-azurermstorageaccount

The reason why teachers have a reset-Azure dilemma, is that reset-Azure takes around half an hour or more. From West-Europe data centers from august until december this happens every week. So after finishing a module and need time to setup-Azure for the Next module, some teachers prefer to skip reset-Azure.

Met vriendelijke groet,
Marcel Molenaar
IT training, coaching & consultancy
06-24654633
info@marcelmolenaar.com<mailto:info@marcelmolenaar.com>
www.marcelmolenaar.com<http://www.marcelmolenaar.com>

________________________________

**Comment by polichtm** [comment]
Marcel - appreciate the input and we will take into account. However, in this particular case, as far as I can tell, the error results from the mistake made in the previous task of the same exercise - and does not really have anything to do with Setup-Azure or Reset-Azure
rgds
Marcin
